# Generated by Django 5.1.4 on 2024-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
