# Generated by Django 5.1.4 on 2024-12-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tags',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
