# Generated by Django 5.1.4 on 2025-01-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_gasto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('TC_BHD', 'Tarjeta Crédito BHD'), ('TC_BSC', 'Tarjeta Crédito BSC'), ('TC_BANRESERVAS', 'Tarjeta Crédito Banreservas')], default='Efectivo', max_length=20),
        ),
    ]
